kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: mern-app-ingress
  namespace: nodejs-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: react-vite-service
                port:
                  number: 80
          - pathType: Prefix
            path: /mern
            backend:
              service:
                name: nodejs-app-service
                port:
                  number: 6000
