apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-vite-deployment
  labels:
    app: react-vite
  namespace: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-vite
  template:
    metadata:
      labels:
        app: react-vite

    spec:
      containers:
        - name: react-vite
          image: rj1608/react-vite-k8s
          ports:
            - containerPort: 80
