kind: Service
apiVersion: v1
metadata:
  name: react-vite-service
  namespace: nodejs-app
spec:
  selector:
    app: react-vite
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
